export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_USER = "SET_USER";
export const SET_USER_PLAYLISTS = "SET_USER_PLAYLISTS";
export const SET_USER_LIKED_SONGS = "SET_USER_LIKED_SONGS";
export const SET_CURRENT_TRACK = "SET_USER_CURRENT_TRACK";
